name: Generate Screenshots

on:
  pull_request:
    branches:
      - master
    types:
      - closed

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  screenshots:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch full history to ensure all commits are accessible

      # Install Puppeteer
      - name: Install Puppeteer
        run: npm install puppeteer

      # Install Sharp
      - name: Install Sharp
        run: npm install sharp

      # Run Puppeteer script to generate screenshots
      - name: Generate screenshots
        run: node generators/generateScreenshot.js

      - name: Commit and Push Screenshots
        run: |
          # # Configure git
          # git config --global user.name "GitHub Actions"
          # git config --global user.email "actions@github.com"

          # Check for changes
          # git pull

          # Add changes
          git add Art/**/icon.png

          # Commit changes if there are any
          git commit -m "(CI) Screenshot Generation" || echo "No changes to commit"

          # Push changes
          git push
