name: Generate Includes

on:
  pull_request:
    branches:
      - master
    types:
      - closed
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  generateIncludes:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Run the script to generate cards.json
      - name: Generate cards.json
        run: node generators/generateCards.js

      # # Configure Git
      # - name: Configure Git
      #   run: |
      #     git config --global user.name "GitHub Actions"
      #     git config --global user.email "actions@github.com"

      # Check if there are changes in public/cards.json
      - name: Check for changes
        run: |
          if git diff --quiet public/cards.json; then
            echo "No changes to commit"
          else
            git add public/cards.json
            git commit -m "(CI) cards.json Generation"
            git push
          fi
